# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demo < Formula
  desc ""
  homepage "https://github.com/shibme/demo-cli"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shibme/demo-cli/releases/download/v1.0.0/demo_1.0.0_darwin_arm64.zip"
      sha256 "5fa32b5b4d66321ea8f55eaab15e7bc5bc06a549184645f15792576bd36cad90"

      def install
        bin.install "demo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shibme/demo-cli/releases/download/v1.0.0/demo_1.0.0_darwin_amd64.zip"
      sha256 "56bb65e2b7511191271fd849ba0647b66f12408f89c31aaf90aaf0e21cdf3cd3"

      def install
        bin.install "demo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/demo-cli/releases/download/v1.0.0/demo_1.0.0_linux_arm64.zip"
      sha256 "c8fbe1dc8d9b9961bb4e919362edb9289ab835b64a934d67390326dc854d825a"

      def install
        bin.install "demo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shibme/demo-cli/releases/download/v1.0.0/demo_1.0.0_linux_amd64.zip"
      sha256 "a296e75be597cab3b3c1dd85a18a6169051bba056bc55221dbbbe24b4164a71b"

      def install
        bin.install "demo"
      end
    end
  end
end
