# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demo < Formula
  desc ""
  homepage "https://github.com/shibme/demo-cli"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shibme/demo-cli/releases/download/v1.0.2/demo_1.0.2_darwin_arm64.zip"
      sha256 "faecaaf7f3d63c8189804f7561b29af514e3c52988341b5d7e1a18925cba2b82"

      def install
        bin.install "demo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shibme/demo-cli/releases/download/v1.0.2/demo_1.0.2_darwin_amd64.zip"
      sha256 "79b7daeece4565ab44c720ec8e49ca46addd0162c5d598877e56843bd2f47af9"

      def install
        bin.install "demo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/demo-cli/releases/download/v1.0.2/demo_1.0.2_linux_arm64.zip"
      sha256 "475e918c498c00159947e0d34e6b7e9cf8feca292aa225c64afd3e0e792dee46"

      def install
        bin.install "demo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shibme/demo-cli/releases/download/v1.0.2/demo_1.0.2_linux_amd64.zip"
      sha256 "c2abc6f7667a130326c8da477d9b5f310cb5b70fbc5604b48924af1aee8fd484"

      def install
        bin.install "demo"
      end
    end
  end
end
