# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demo < Formula
  desc ""
  homepage ""
  version "1.2.0"

  on_macos do
    on_intel do
      url "https://github.com/shibme/demo-cli/releases/download/v1.2.0/demo-cli_darwin_amd64.zip"
      sha256 "0513887939a5a834c4a0b3f4554c7ecca72425e51b85c0c493b932bfb51864da"

      def install
        bin.install "demo"
      end
    end
    on_arm do
      url "https://github.com/shibme/demo-cli/releases/download/v1.2.0/demo-cli_darwin_arm64.zip"
      sha256 "b443e25b2e3bd5f769944bcbc5f4ae5104890ddbd882153039f0e136fcc5a71a"

      def install
        bin.install "demo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/demo-cli/releases/download/v1.2.0/demo-cli_linux_amd64.zip"
        sha256 "201f2d94ec0edc4d203317a8405e585358fe9923135e361938ae8d8ab4122f99"

        def install
          bin.install "demo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/demo-cli/releases/download/v1.2.0/demo-cli_linux_arm64.zip"
        sha256 "1293cf865e9db108c2b7cfbe64b49613543e977beba57b73843e85f0634fee1b"

        def install
          bin.install "demo"
        end
      end
    end
  end
end
