# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Randgen < Formula
  desc "RandGen is a simple CLI tool to generate random files of a given size."
  homepage "https://dev.shib.me/randgen"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shibme/randgen/releases/download/v0.0.1/randgen_darwin_amd64.zip"
      sha256 "96b3b97f3fa4db7f06088ea68c95dbffa0f4ea079d84542b650a20750db0452b"

      def install
        bin.install "randgen"
      end
    end
    on_arm do
      url "https://github.com/shibme/randgen/releases/download/v0.0.1/randgen_darwin_arm64.zip"
      sha256 "450499885f73f5fabacaacfc7206e8d7b76378b33544a905fcf16b22b7efee47"

      def install
        bin.install "randgen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/randgen/releases/download/v0.0.1/randgen_linux_amd64.zip"
        sha256 "3b21894d78d3474e57c35364a33706edd55371f187ebc5c3ee44c51f72c48dc8"

        def install
          bin.install "randgen"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/randgen/releases/download/v0.0.1/randgen_linux_arm.zip"
        sha256 "e8d1a53152cdab5e80d417a6999c18ef9a63d9307e95742bd1d0b3657c97b9e7"

        def install
          bin.install "randgen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/randgen/releases/download/v0.0.1/randgen_linux_arm64.zip"
        sha256 "0f7fc3aecfe7a6bc534f1d07facccd94b0cc230925eb2421b09f8f6f68171485"

        def install
          bin.install "randgen"
        end
      end
    end
  end
end
