# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Randgen < Formula
  desc "RandGen is a simple CLI tool to generate random files of a given size."
  homepage "https://dev.shib.me/randgen"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shibme/randgen/releases/download/v0.1.0/randgen_darwin_amd64.zip"
      sha256 "4c0ac6f677e527d184ffcddc9b83fee8cd451bc28ad9a0a0bafa2d92add0e736"

      def install
        bin.install "randgen"
      end
    end
    on_arm do
      url "https://github.com/shibme/randgen/releases/download/v0.1.0/randgen_darwin_arm64.zip"
      sha256 "e19a4b9648a08ca15d42fc630a40ebcfbe26d862e6911af40ef5559b3470423a"

      def install
        bin.install "randgen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/randgen/releases/download/v0.1.0/randgen_linux_amd64.zip"
        sha256 "07e6c49d7f1415f5610d4e0a25e96467134b8289e8f075e30b047d93e4029c9f"

        def install
          bin.install "randgen"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/randgen/releases/download/v0.1.0/randgen_linux_arm.zip"
        sha256 "db414374be1a2c3a5b8cf239eead68e465464af23079e0998d0da2d5403145e6"

        def install
          bin.install "randgen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/randgen/releases/download/v0.1.0/randgen_linux_arm64.zip"
        sha256 "5eee4a1b03f278224d013aae8c7fbb51cdb9347bb2303b24cb5fd62e8628368f"

        def install
          bin.install "randgen"
        end
      end
    end
  end
end
